name: openwrt
on:
  push:
   branches:
    - master
  pull_request:
    branches: 
    - master 
jobs:
   build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: push dns
      run: 
       pwd='${{ secrets.PWD }}'
       pushd tmp
       git clone https://github.com/yuhongwei380/openwrt-profile.git
       pwd
    - name: scp dns
      run:   
       pushd openwrt-profile/
       sshpass -p "$PWD" scp  dns/dhcp    root@192.168.15.253:/etc/config/
       sshpass -p "$PWD" ssh root@192.168.15.253 "/etc/init.d/dnsmasq restart"
       
    - name: push ssr
      run:
       pwd='${{ secrets.PWD }}'
       pushd tmp
      #git clone https://github.com/yuhongwei380/openwrt-profile.git
       pwd
    - name: push ssr
      run:
       pushd openwrt-profile/
       sshpass -p "$PWD" scp  ssr/black.list     root@192.168.15.253:/etc/ssrplus/
       sshpass -p "$PWD" ssh root@192.168.15.253 "/etc/init.d/shadowsocksr restart"