name: openwrt
on:
  push:
   branches:
    - master
  pull_request:
    branches: 
    - master 
jobs:
   build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: push dns
      run:
       pwd='${{ secrets.PWD }}'
       cd /tmp/ $$ git clone https://github.com/yuhongwei380/openwrt-profile.git
       sshpass -p "$PWD" scp  /tmp/dns/dhcp    root@192.168.15.253:/etc/config/
       sshpass -p "$PWD" ssh root@192.168.15.253 "/etc/init.d/dnsmasq restart"
    
    - name: push ssrplus
      run:
       pwd='${{ secrets.PWD }}'
       cd /tmp/ && sshpass -p "$PWD" scp  /tmp/ssr/black.list    root@192.168.15.253:/etc/ssrplus/
       sshpass -p "$PWD" ssh root@192.168.15.253 "/etc/init.d/shadowsocksr restart"